import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={ `bg-slate-200 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-full sm:max-w-md mx-auto p-4 bg-white text-black">
          {children}
        </div>
      </body>
    </html>
  );
}
